# Generated by Django 5.2.11 on 2026-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='lead',
            name='builder',
            field=models.CharField(blank=True, choices=[('RUNWAL', 'Runwal'), ('SAI PARADISE', 'Sai Paradise'), ('LODHA', 'Lodha'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='flat_type',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('1.5BHK', '1.5BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], default='1BHK', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='other_builder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='purpose',
            field=models.CharField(choices=[('RENT', 'Rent'), ('RESALE', 'Resale'), ('NEW', 'New')], default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(default='dashboard', max_length=50),
        ),
        migrations.AlterField(
            model_name='builder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
