# Generated by Django 5.2.11 on 2026-02-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0003_alter_builder_id_alter_campaign_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_leads',
            field=models.IntegerField(default=0),
        ),
    ]
