# Generated by Django 5.2.11 on 2026-02-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0005_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
