# Generated by Django 5.2.11 on 2026-02-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0006_campaign_executed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='purpose',
            field=models.CharField(choices=[('RENT', 'Rent'), ('RESALE', 'Resale'), ('NEW', 'New')], default='NEW', max_length=20),
        ),
    ]
