# Generated by Django 5.2.11 on 2026-02-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0007_alter_lead_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], max_length=20)),
                ('image', models.ImageField(upload_to='rent/images/')),
                ('blueprint', models.ImageField(null=True, upload_to='rent/blueprints/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResaleFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], max_length=20)),
                ('image', models.ImageField(upload_to='resale/images/')),
                ('blueprint', models.ImageField(null=True, upload_to='resale/blueprints/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
