# Generated by Django 5.2.11 on 2026-02-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0008_rentflat_resaleflat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentflat',
            name='deposite',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
    ]
