# Generated by Django 5.2.11 on 2026-02-06 17:37

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0009_rentflat_deposite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='blueprint',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1000, 800], upload_to='flats/blueprints/'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[800, 600], upload_to='flats/images/'),
        ),
    ]
