# Generated by Django 5.2.11 on 2026-02-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0010_alter_flat_blueprint_alter_flat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentflat',
            name='blueprint',
        ),
        migrations.RemoveField(
            model_name='resaleflat',
            name='blueprint',
        ),
    ]
