# Generated by Django 5.2.11 on 2026-02-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0011_remove_rentflat_blueprint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentflat',
            old_name='monthly_price',
            new_name='monthly_rent',
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.CharField(help_text='Example: 45 Lac, 56 Lac, 1 Cr, 2.5 Cr', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentflat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_module.category'),
        ),
        migrations.AlterField(
            model_name='resaleflat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_module.category'),
        ),
        migrations.AlterField(
            model_name='resaleflat',
            name='price',
            field=models.CharField(help_text='Example: 45 Lac, 56 Lac, 1 Cr, 2.5 Cr', max_length=20),
        ),
    ]
