# Generated by Django 5.2.11 on 2026-02-07 08:40

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0012_rename_monthly_price_rentflat_monthly_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='blueprint',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1000, 800], upload_to='flats/blueprints/'),
        ),
    ]
